# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-24 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display', models.CharField(choices=[('full_image', 'full_image'), ('image_text', 'image_text')], default='image_text', max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('image_alt', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('full_text', models.TextField()),
            ],
        ),
    ]
